Repository BookKitty/BookKitty-iOS, pull requests merged in 2025-02, with the labels that each got.

#9 [Feat] 질문 내역 뷰모델 구현
  BookKitty/.swiftlint.yml
  BookKitty/BookKitty/Source/Common/Model/Question.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Feature/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Repository/MockQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
  BookKitty/BookKittyTests/ViewModelTests/QuestionHistoryViewModelTests.swift
Labels: feature

#7 [Feat] 내 서재 화면의 뷰모델 작성
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/Network/Package.resolved
  BookKitty/BookKitty/Network/Package.swift
  BookKitty/BookKitty/Source/Coordinator/BookCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/TabBarCoordinator.swift
  BookKitty/BookKitty/Source/Feature/BookList/ViewModel/BookListViewModel.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift
  BookKitty/BookKitty/Source/Repository/DefaultBookRepository.swift
  BookKitty/BookKitty/Source/Repository/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift
  BookKitty/BookKittyTests/ViewModelTests/MyLibraryViewModelTests.swift
Labels: feature

#12 [Feat] Floating 관련 UI 상태 동기화 및 애니메이션 구현
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/DimmingView.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/FloatingButton.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/FloatingMenu.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/FloatingMenuItem.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/FloatingMenuItemType.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/FloatingMenu/FloatingMenu.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/TabBarController.swift
Labels: feature

#11 [Feat] 책 추천 화면 뷰모델 작성
  BookKitty/BookKitty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Common/BaseComponents/ViewModelType.swift
  BookKitty/BookKitty/Source/Common/Model/QuestionAnswer.swift
  BookKitty/BookKitty/Source/Feature/Recommendation/ViewModel/RecommendationViewModel.swift
  BookKitty/BookKitty/Source/Repository/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionRepository.swift
  BookKitty/BookKittyTests/ViewModelTests/RecommendationViewModelTests.swift
Labels: feature

#14 [Feat] 질문 추가 플로우 Coordinator 구현
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/BookCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/TabBarCoordinator.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/ViewModel/BookDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
  BookKitty/BookKitty/Source/Feature/NewQuestion/ViewModel/NewQuestionViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/View/QuestionDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuesetionResultController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Floating/FloatingMenuItemType.swift
  BookKitty/BookKitty/Source/Feature/TabBar/ViewModel/TabBarViewModel.swift
Labels: bug, feature

#17 [Chore] 도서 매칭 시스템 패키지 로컬 배포
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/BookMatchKit/.gitignore
  BookKitty/BookKitty/BookMatchKit/Package.resolved
  BookKitty/BookKitty/BookMatchKit/Package.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Configuration/APIConfiguration.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Constants/Prompts.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/DTOs/ChatGPTResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/DTOs/ChatMessage.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/DTOs/NaverBookResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchError/BookMatchError.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Configuration/BookMatchConfiguration.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/Book.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/BookMatchModuleInputOutput.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/GPTRecommendation.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/BookMatchable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/ImageSimilarityCalculatable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/SimilarityCalculatable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchModule.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/BookImageSimilarityCalculator.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategyWithNoParenthesis.swift
  BookKitty/BookKitty/BookMatchKit/config.swiftformat
Labels: feature

#20 [Fix] test 파일 추가
  BookKitty/BookKitty/BookMatchKit/Tests/BookMatchKitTests/BookMatchKitTests.swift
Labels: fix

#23 [Feat] QuestionHistoryViewController 구현
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryCell.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
  BookKitty/BookKitty/Source/Repository/MockQuestionHistoryRepository.swift
Labels: feature

#26 [Feat] BookMatchKit 고도화
  BookKitty/BookKitty/BookMatchKit/Package.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/BookMatchable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/BookRecommendable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/ImageSimilarityCalculatable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Protocols/SimilarityCalculatable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategyWithNoParenthesis.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/BookMatchKit/Tests/BookMatchKitTests/BookMatchKitTests.swift
Labels: feature

#24 [Feat] 질문 결과 화면 구현
  BookKitty/.swiftlint.yml
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/BookMatchKit/Package.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UILabel/BodyLabel.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UILabel/OwnedTagLabel.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIView/RecommendedBookView.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIView/UserQuestionView.swift
  BookKitty/BookKitty/Source/Common/Model/Book.swift
  BookKitty/BookKitty/Source/Common/Model/Question.swift
  BookKitty/BookKitty/Source/Common/Model/QuestionAnswer.swift
  BookKitty/BookKitty/Source/Common/Service/Mock/MockRecommendationService.swift
  BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/DesignSample/ImageSampleViewController.swift
  BookKitty/BookKitty/Source/DesignSample/LabelSample2ViewController.swift
  BookKitty/BookKitty/Source/DesignSample/ViewSampleViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/SectionOfBook.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuesetionResultController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/RecommendedBookCell.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Feature/Recommendation/ViewModel/RecommendationViewModel.swift
  BookKitty/BookKitty/Source/Repository/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/MockQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionRepository.swift
  BookKitty/BookKittyTests/BookKittyTests.swift
  BookKitty/BookKittyTests/ViewModelTests/NewQuestionViewModelTests.swift
  BookKitty/BookKittyTests/ViewModelTests/QuestionHistoryViewModelTests.swift
  BookKitty/BookKittyTests/ViewModelTests/RecommendationViewModelTests.swift
Labels: feature

#27 [Feat] 질문 디테일 뷰 구현
  BookKitty/BookKitty/Source/Common/DateFormatHandler.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/View/QuestionDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Repository/MockQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
  BookKitty/BookKittyTests/ViewModelTests/QuestionDetailViewModelTests.swift
  BookKitty/BookKittyTests/ViewModelTests/RecommendationViewModelTests.swift
Labels: feature

#31 [Fix] Sendable 관련 오류 수정
  BookKitty/BookKitty/BookMatchKit/Package.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ChatGPTEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ImageDownloadEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/NaverBooksEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
Labels: fix

#34 [Feat] 홈화면 구현
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
  BookKitty/BookKitty/Source/Feature/Home/ViewModel/HomeViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
Labels: feature

#37 [Fix] Network 에러 수정 및 홈화면에 저작권 텍스트 추가
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Implementation/DefaultAPIClient.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/ChatGPTEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Models/NaverBooksEndpoint.swift
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
Labels: fix

#42 [Feat] BookDetail 화면 바인딩
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIView/ManageBookPopupView.swift
  BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/BookCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailInfoView.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/ViewModel/BookDetailViewModel.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
  BookKitty/BookKittyTests/ViewModelTests/BookDetailViewModelTests.swift
Labels: feature

#44 [Feat] CustomNavigationBar 구현
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/Common/CustomNavigationBar.swift
  BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/View/QuestionDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
Labels: feature, refactor

#46 [Fix] 초기 인디케이터가 보이지 않는 문제 수정
  BookKitty/BookKitty/Source/Feature/TabBar/View/Tab/TabBarView.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/TabBarController.swift
Labels: fix

#48 [Feat] QnA 히스토리 추가 / 삭제 기능 점검
  BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Common/Utility/BookKittyLogger.swift
  BookKitty/BookKitty/Source/Common/Utility/DateFormatHandler.swift
  BookKitty/BookKitty/Source/Common/Utility/Environment.swift
  BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/BookCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryCell.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Persistence/BookCoreDataManager.swift
  BookKitty/BookKitty/Source/Persistence/BookQALinkCoreDataManager.swift
  BookKitty/BookKitty/Source/Persistence/CoreDataStack.swift
  BookKitty/BookKitty/Source/Persistence/Protocol/BookCoreDataManageable.swift
  BookKitty/BookKitty/Source/Persistence/Protocol/BookQALinkCoreDataManageable.swift
  BookKitty/BookKitty/Source/Persistence/Protocol/QuestionAnswerCoreDataManageable.swift
  BookKitty/BookKitty/Source/Persistence/QuestionAnswerCoreDataManager.swift
  BookKitty/BookKitty/Source/Repository/LocalBookRepository.swift
  BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
Labels: feature

#49 [Fix] 질문 답변 책 데이터 가져오기 오류 수정
  BookKitty/BookKitty/Source/Persistence/BookQALinkCoreDataManager.swift
Labels: feature

#50 [Feat] 홈 뷰에서 최근 추천받은 책 목록 보여주기 구현
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
  BookKitty/BookKitty/Source/Feature/Home/ViewModel/HomeViewModel.swift
Labels: feature

#51 [Refactor] BookDeatil 데이터 포맷터, NewQuestion 질문 최소 글자 수 적용
  BookKitty/BookKitty/Source/Common/Utility/DateFormatHandler.swift
  BookKitty/BookKitty/Source/Common/Utility/NumberFormatHandler.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailInfoView.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
Labels: refactor

#55 [Fiex] 순환참조 수정
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/ViewModel/BookDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/Home/ViewModel/HomeViewModel.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift
  BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Feature/ReviewAddBook/ViewModel/ReviewAddBookViewModel.swift
Labels: fix

#56 ocr upgrade
  BookKitty/BookKitty/Source/Feature/AddBook/View/BaseCameraViewController.swift
Labels: feature

#63 [Feat] 에러 알림 뷰컨 구현
  BookKitty/BookKitty/Source/Common/Error/ErrorAlertController.swift
Labels: feature

#64 [Refactor] BaseCameraViewController 삭제 및 병합 & BookMatchKit 연결
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchError/BookMatchError.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Extensions/UIImage+.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/BookMatchable.swift
  BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/BaseCameraViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
Labels: fix

#65 [Feat] 알림 처리에 사용될 에러 프로토콜 정의
  BookKitty/BookKitty/Source/Common/Error/Component/ErrorAlertController.swift
  BookKitty/BookKitty/Source/Common/Error/DataError.swift
  BookKitty/BookKitty/Source/Common/Error/NetworkError.swift
  BookKitty/BookKitty/Source/Common/Error/Protocol/AlertPresentableError.swift
Labels: feature

#68 [Refactor] BookMatchKit 에러처리 및 리펙토링
  BookKitty/BookKitty/BookMatchKit/Package.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Base/APIConfiguration.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Base/BaseAPIClient.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/AIRecommendable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/APIClientProtocol.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/BookSearchable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/ImageDownloadable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/Endpoint/ImageDownloadEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/ImageDownloadAPI.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/Naver/Endpoint/NaverBooksEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/Naver/Models/NaverBookResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/Naver/NaverBookAPI.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Constants/Prompts.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Endpoint/OpenAIEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/OpenAIResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/RawAiResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/OpenAIAPI.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchError/BookMatchError.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Configuration/BookMatchConfiguration.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/Models/BookMatchModuleOutput.swift
Labels: fix, refactor

#72 [Refactor] BookMatchKit 내부 모델 명칭 일관되게 통일
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Protocols/AIRecommendable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/Naver/Models/NaverBookResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/OpenAIResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/RawAiResponse.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/RecommendationForQuestionRaw.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/Models/RecommendationFromOwnedRaw.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/OpenAI/OpenAIAPI.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Extensions/UIImage+.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/BookItem.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/OwnedBook.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/RawBook.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/RecommendationForQuestion.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Models/RecommendationFromOwned.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/NetworkKit/Tests/NetworkKitTests/Component/TestConstant.swift
Labels: refactor

#71 [Refactor] MVP 기준 QAList 리팩토링
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryCell.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Tab/GradientView.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/Tab/TabBarView.swift
  BookKitty/BookKitty/Source/Feature/TabBar/View/TabBarController.swift
Labels: feature, refactor

#74 [Fix] 도서 매칭 로직 수정
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/Endpoint/ImageDownloadEndpoint.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/Extensions/UIImage+.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/BookMatchable.swift
  BookKitty/BookKitty/NetworkKit/Sources/NetworkKit/NetworkManager.swift
  BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/ReviewAddBook/View/ReviewAddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/ReviewAddBook/ViewModel/ReviewAddBookViewModel.swift
Labels: fix

#80 [Refactor] BookMatchKit 내부 Logger 구현 및 연결
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchLogger.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/NetworkKit/Sources/NetworkKit/Component/NetworkEventLogger.swift
  BookKitty/BookKitty/NetworkKit/Sources/NetworkKit/NetworkManager.swift
Labels: feature, refactor

#79 [Feat] 런치 스크린 이미지 적용
  BookKitty/BookKitty/App/Base.lproj/LaunchScreen.storyboard
  BookKitty/BookKitty/Resource/Assets.xcassets/launchImage.imageset/Contents.json
  BookKitty/BookKitty/Resource/Assets.xcassets/launchImage.imageset/launchImage.png
  BookKitty/BookKitty/Resource/Assets.xcassets/launchImage.imageset/launchImage@2x.png
  BookKitty/BookKitty/Resource/Assets.xcassets/launchImage.imageset/launchImage@3x.png
Labels: feature

#77 [Refactor] 키보드 활성화시 버튼 탭 리팩토링
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/App/Info.plist
  BookKitty/BookKitty/Source/Feature/NewQuestion/View/NewQuestionViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
Labels: feature, refactor

#81 [Feat] 질문 결과 뷰 에러 처리
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/Source/Common/Error/AddBookError.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
Labels: feature

#84 [Feat] 홈뷰 책 없음 구현
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
Labels: feature

#83 [Feat] EmptyDataDescriptionView 구현"
  BookKitty/BookKitty/Source/Feature/Common/EmptyDataDescriptionView.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
Labels: feature

#85 [Feat] 백그라운드 색상 다시 롤백
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
Labels: feature

#87 [Refactor] BookMatchKit 리펙토링
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchAPI/Services/ImageDownload/ImageDownloadAPI.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchError/BookMatchError.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchLogger.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/BookMatchKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/BookMatchable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/ImageProcessable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Protocols/TextExtractable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Utils/ImageProcessor.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchKit/Utils/TextExtractor.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/LevenshteinStrategyWithNoParenthesis.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/Protocols/SimilarityCalculatable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchStrategy/VisionImageStrategy.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookRecommendationKit/BookRecommendationKit.swift
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
  BookKitty/PrivacyInfo.xcprivacy
Labels: refactor

#90 [Feat] 사진 추가 뷰 디자인 변경
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/Common/CustomNavigationBar.swift
Labels: feature

#93 [Fix] KingFisher UIImageView 3개 높이, 너비 업데이트 로직 일괄 변경
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/FlexibleImageView.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/HeightFixedImageView.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UIImageView/WidthFixedImageView.swift
Labels: fix

#95 feat:ocr add features
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Service/TextExtractionService.swift
Labels: feature

#96 [Feat] Query로 책 검색결과 추가 구현
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Protocols/BookSearchable.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Service/BookSearchService.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookOCRKit/BookOCRKit.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookOCRKit/Protocols/BookMatchable.swift
Labels: feature

#99 fix:camera bug
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/ViewModel/AddBookViewModel.swift
Labels: fix

#98 [Feat] 제목으로 책 추가하기 기능 구현
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Service/BookSearchService.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookOCRKit/BookOCRKit.swift
  BookKitty/BookKitty/Source/Common/Model/Book.swift
  BookKitty/BookKitty/Source/Common/Service/Mock/MockBookOCRKit.swift
  BookKitty/BookKitty/Source/Common/Service/Mock/MockRecommendationService.swift
  BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/AddBookByTitleCell.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/AddBookByTitleViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/Popup/AddBookConfirmView.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/Popup/AddBookConfirmViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/ViewModel/AddBookByTitleViewModel.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/View/BookDetailViewController.swift
  BookKitty/BookKitty/Source/Feature/Common/CustomNavigationBar.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
Labels: feature

#97 [Fix] QuestionResult 에러 핸들링 수정, QuestionHistoryCell 재사용 전처리 로직 추가
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty/NetworkKit/Sources/NetworkKit/NetworkManager.swift
  BookKitty/BookKitty/Source/Common/Error/Component/ErrorAlertController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryCell.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
Labels: fix

#100 [Fix] 책 중복 에러 잘 표시되도록 변경
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/Popup/AddBookConfirmViewController.swift
Labels: bug

#102 [Fix] 스크롤 계속해서 내려가는 현상 수정, 런치스크린 백그라운드 적용
  BookKitty/BookKitty/App/Base.lproj/LaunchScreen.storyboard
  BookKitty/BookKitty/Source/Feature/QuestionResult/View/QuestionResultViewController.swift
Labels: fix

#103 [Fix] QnA 히스토리 헤더 스크롤에서 분리
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
Labels: fix

#104 [Feat] 에러 로그 적용 및 print -> Logger 변경
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchCore/BookMatchLogger.swift
  BookKitty/BookKitty/BookMatchKit/Sources/BookMatchService/Service/TextExtractionService.swift
  BookKitty/BookKitty/DesignSystem/Package.resolved
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Common/DSLogger.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Extension/String+Extensions.swift
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Extension/UIFont+Extensions.swift
  BookKitty/BookKitty/Source/DesignSample/AlertSampleViewController.swift
  BookKitty/BookKitty/Source/DesignSample/ButtonSampleViewController.swift
  BookKitty/BookKitty/Source/DesignSample/EtcSampleViewController.swift
  BookKitty/BookKitty/Source/DesignSample/ImageSampleViewController.swift
  BookKitty/BookKitty/Source/DesignSample/LabelSample1ViewController.swift
  BookKitty/BookKitty/Source/DesignSample/LabelSample2ViewController.swift
  BookKitty/BookKitty/Source/DesignSample/ViewSampleViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBook/ViewModel/AddBookViewModel.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/Popup/AddBookConfirmViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/ViewModel/AddBookByTitleViewModel.swift
  BookKitty/BookKitty/Source/Feature/BookDetail/ViewModel/BookDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/Guide/View/GuideViewController.swift
  BookKitty/BookKitty/Source/Feature/Guide/ViewModel/GuideViewModel.swift
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionDetail/ViewModel/QuestionDetailViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
Labels: feature

#105 [Fix] 머지 후 이슈 수정
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
Labels: fix

#106 [Fix] 오프셋 이슈 수정
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryCollectionViewCell.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
Labels: feature, fix

#108 [Feat] Firebase 로깅 시스템 구축
  BookKitty/BookKitty.xcodeproj/project.pbxproj
  BookKitty/BookKitty.xcodeproj/xcshareddata/xcschemes/BookKitty.xcscheme
  BookKitty/BookKitty/App/AppDelegate.swift
  BookKitty/BookKitty/Source/Common/BaseComponents/BaseViewController.swift
  BookKitty/BookKitty/Source/Coordinator/AddBookCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/AddQuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/AppCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/HomeCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/MyLibraryCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/Protocol/Coordinator.swift
  BookKitty/BookKitty/Source/Coordinator/QuestionCoordinator.swift
  BookKitty/BookKitty/Source/Coordinator/TabBarCoordinator.swift
  BookKitty/BookKitty/Source/Feature/Home/View/HomeViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/View/MyLibraryViewController.swift
  BookKitty/BookKitty/Source/Feature/MyLibrary/ViewModel/MyLibraryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/View/QuestionHistoryViewController.swift
  BookKitty/BookKitty/Source/Feature/QuestionHistory/ViewModel/QuestionHistoryViewModel.swift
  BookKitty/BookKitty/Source/Feature/QuestionResult/ViewModel/QuestionResultViewModel.swift
  BookKitty/BookKitty/Source/Persistence/BookCoreDataManager.swift
  BookKitty/BookKitty/Source/Persistence/Protocol/BookCoreDataManageable.swift
  BookKitty/BookKitty/Source/Persistence/Protocol/QuestionAnswerCoreDataManageable.swift
  BookKitty/BookKitty/Source/Persistence/QuestionAnswerCoreDataManager.swift
  BookKitty/BookKitty/Source/Repository/LocalBookRepository.swift
  BookKitty/BookKitty/Source/Repository/LocalQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockBookRepository.swift
  BookKitty/BookKitty/Source/Repository/Mock/MockQuestionHistoryRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/BookRepository.swift
  BookKitty/BookKitty/Source/Repository/Protocol/QuestionHistoryRepository.swift
  BookKitty/GoogleService-Info.plist
Labels: feature

#107 [Fix] 제목으로 책 추가하기 화면 다크모드 이슈 해결 및 디자인 개선
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Resource/Images.xcassets/searchIcon.imageset/Contents.json
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Resource/Images.xcassets/searchIcon.imageset/icon.svg
  BookKitty/BookKitty/DesignSystem/Sources/DesignSystem/Source/Component/UISerachBar/CustomSearchBar.swift
  BookKitty/BookKitty/Source/Feature/AddBook/View/AddBookViewController.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/AddBookByTitleCell.swift
  BookKitty/BookKitty/Source/Feature/AddBookByTitle/View/AddBookByTitleViewController.swift
Labels: feature, fix
